#  Forward pass

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Deep Learning with PyTorch (2020) Авторы: Eli Stevens, Luca Antiga, Thomas Viehmann
* https://pytorch.org/docs/stable/generated/torch.matmul.html
* https://machinelearningmastery.com/choose-an-activation-function-for-deep-learning/
* https://machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/

## Задачи для совместного разбора

1\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте нейрон с заданными весами `weights` и `bias`. Пропустите вектор `inputs` через нейрон и выведите результат.

In [ ]:
import torch

In [ ]:
class Neuron(object):
  def __init__(self, weights, bias):
    self.weights = weights
    self.bias = bias

  def forward(self, inputs):
    return inputs @ self.weights + self.bias

In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])   #
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])   # веса
bias = 3.14   # сдвиг

In [ ]:
neuron = Neuron(weights, bias)
neuron.forward(inputs)

tensor(4.8400)

2\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

In [ ]:
class ReLU:
  def forward(self, inputs):
    # <реализовать логику ReLU>
    return torch.clip(inputs, min=0)   # обрезвает значения <0 до 0,

In [ ]:
t = torch.normal(0, 1, size=(4, 3))
t

tensor([[ 1.7329,  0.7491, -1.8803],
        [ 0.9101, -0.0414,  0.2754],
        [-0.9300,  0.2888,  1.1036],
        [ 0.3720,  1.3585,  0.0356]])

In [ ]:
ReLU().forward(t)

tensor([[1.7329, 0.7491, 0.0000],
        [0.9101, 0.0000, 0.2754],
        [0.0000, 0.2888, 1.1036],
        [0.3720, 1.3585, 0.0356]])

3\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)
где $Y_i$ - правильный ответ для примера $i$, $\hat{Y_i}$ - предсказание модели для примера $i$, $n$ - количество примеров в батче.

In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return ((y_pred - y_true) ** 2).sum() / len(y_pred)

In [ ]:
y_pred = torch.tensor([1.0, 3.0, 5.0])
y_true = torch.tensor([2.0, 3.0, 4.0])

In [ ]:
MSELoss().forward(y_pred, y_true)

tensor(0.6667)

## Задачи для самостоятельного решения

### Cоздание полносвязных слоев

<p class="task" id="1_1"></p>

1\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения) и опциональным вектором смещения.

$$y = xW^T + b$$

Пропустите вектор `inputs` через слой и выведите результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [ ]:
  import torch as th

In [ ]:
class Linear:
    def __init__(self, n_neurons, n_features, bias: bool = False):
      self.weights = th.normal(0, 1, size = (n_neurons, n_features))
      # self.bias = bias   # вектор смещения
      if bias == True:
        self.bias = th.randn(n_neurons)   # столько же сколько и входных нейронов
      else:
        self.bias = th.zeros(n_neurons)


    def forward(self, inputs):
        # print(inputs @ self.weights.T, self.bias)
        return inputs @ self.weights.T + self.bias

In [ ]:
# # inputs: batch_size(3) x 4
inputs = th.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])


In [ ]:
Linear(5, inputs.shape[1],True).forward(inputs)

tensor([[ 2.5480e+00,  8.0323e+00, -1.1452e-02, -4.1048e+00, -1.4267e+00],
        [ 4.7221e+00,  1.0099e+01, -1.2419e+01, -2.0714e+00, -4.3026e+00],
        [ 8.1740e-01, -4.1091e-01,  5.6889e+00, -1.3796e+00,  4.4116e+00]])

In [ ]:
Linear(5, inputs.shape[1],False).forward(inputs)

tensor([[ 0.3200, -3.2305,  7.2585, -2.8210, -2.2018],
        [ 4.3074,  2.9608,  2.1394,  0.4877,  2.6034],
        [-1.3127, -8.7964, 11.5340, -4.0239, -5.2562]])

<p class="task" id="1_2"></p>

1\.2 Используя решение предыдущей задачи, создайте 2 полносвязных слоя и пропустите тензор `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выберите произвольно, количество нейронов во втором слое выберите так, чтобы результатом прогона являлась матрица `batch_size x 7`.

In [ ]:
n_neurons_1 = 5
n_features = inputs.shape[1]
res_1 = Linear(n_neurons_1, n_features, bias = True).forward(inputs)
res_1 , res_1.shape

(tensor([[-3.5682,  0.3726, -7.4296,  0.9823,  0.5379],
         [-1.5626,  3.7613, -3.3729,  6.7235, -2.1885],
         [-1.6287, -4.3252, -9.5480, 10.7022,  6.6696]]),
 torch.Size([3, 5]))

In [ ]:
res_2 = Linear(7, n_neurons_1,True).forward(res_1)
res_2, res_2.shape

(tensor([[  2.9879,  -2.9179,  17.5869,  -1.9476,  -7.6794,  -1.5537,  -0.2832],
         [ -0.1527,  -9.0269,   1.0571,  -5.9935,  -5.3590, -13.9243,   2.2882],
         [ -3.0889,   7.3558,  26.2746,   9.7067, -14.6234,   1.1584,  -3.7482]]),
 torch.Size([3, 7]))

### Создание функций активации

<p class="task" id="2_1"></p>

2\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

$$\overrightarrow{x} = (x_1, ..., x_J)$$

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров. Функция должна применяться переданной на вход матрице построчно.

In [ ]:
import numpy as np

class Softmax:
    def forward(self, inputs):
        # <реализовать логику Softmax>
      exp_x = th.exp(inputs)
      return exp_x / th.sum(exp_x, dim=1, keepdim=True)
        # keepdim результат будет иметь ту же размерность, что и исходный тензор

In [ ]:
x = th.normal(0,1, size = (4,3))
Softmax().forward(x)

tensor([[0.1417, 0.7097, 0.1486],
        [0.3725, 0.3135, 0.3140],
        [0.2757, 0.4244, 0.2999],
        [0.2836, 0.4727, 0.2437]])

In [ ]:
# пpоверка
th.softmax(x, dim = 1)

tensor([[0.1417, 0.7097, 0.1486],
        [0.3725, 0.3135, 0.3140],
        [0.2757, 0.4244, 0.2999],
        [0.2836, 0.4727, 0.2437]])

<p class="task" id="2_1"></p>

2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создайте матрицу размера 4x3, заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

In [ ]:
class ELU:
    def __init__(self, alpha: float):
        self.alpha = alpha

    def forward(self, inputs):
        # <реализовать логику ELU>
        return th.where(inputs >= 0, inputs, self.alpha*(th.exp(inputs) - 1))

In [ ]:
x = th.normal(0,1, size = (4,3))
ELU(alpha = 1.0).forward(x)

tensor([[ 0.4136,  1.2431, -0.1609],
        [-0.5149,  0.0884, -0.7511],
        [ 0.5365,  2.3650, -0.4176],
        [ 1.0363,  0.4290,  0.7961]])

In [ ]:
# проверка
th.nn.ELU()(x)

tensor([[ 0.4136,  1.2431, -0.1609],
        [-0.5149,  0.0884, -0.7511],
        [ 0.5365,  2.3650, -0.4176],
        [ 1.0363,  0.4290,  0.7961]])

### Создание функции потерь

<p class="task" id="3_1"></p>

3\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь CrossEntropyLoss:

$$y_i = (y_{i,1},...,y_{i,k})$$
<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

$$ CrossEntropyLoss = \frac{1}{n}\sum_{i=1}^{n}{L_i}$$
где $y_i$ - вектор правильных ответов для примера $i$, $\hat{y_i}$ - вектор предсказаний модели для примера $i$; $k$ - количество классов, $n$ - количество примеров в батче.

Создайте полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустите через функцию активации Softmax. Посчитайте значение функции потерь, трактуя вектор `y` как вектор правильных ответов.

In [ ]:
class CrossEntropyLoss:
  def forward(self, y_pred, y_true):
    # <реализовать логику функции потерь>

    L = -(y_true*th.log(y_pred)).sum()/len(y_pred)
    return L


In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2],
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])   # y_true вектор правильныз ответов
y_true = y

In [ ]:
out = Linear(n_neurons=3, n_features = inputs.shape[1], bias = False).forward(inputs)
out

tensor([[-3.7170,  7.4250,  6.4598],
        [ 2.8722,  9.6991,  8.6687],
        [-0.6158,  4.3402,  5.5684]])

In [ ]:
y_pred = Softmax().forward(out); y_pred

tensor([[1.0494e-05, 7.2415e-01, 2.7584e-01],
        [7.9838e-04, 7.3640e-01, 2.6280e-01],
        [1.5922e-03, 2.2613e-01, 7.7228e-01]])

In [ ]:
CrossEntropyLoss().forward(y_pred = y_pred, y_true = y_true)

tensor(8.3468)

<p class="task" id="3_2"></p>

3.2 Модифицируйте MSE, добавив L2-регуляризацию.

$$MSE_R = MSE + \lambda\sum_{i=1}^{m}w_i^2$$

где $\lambda$ - коэффициент регуляризации; $w_i$ - веса модели.

In [ ]:
class MSERegularized:
    def __init__(self, lambda_):
        self.lambda_ = lambda_

    def data_loss(self, y_pred, y_true):
        # <подсчет первого слагаемого из формулы>
        return ((y_pred - y_true) ** 2).sum() / len(y_pred)

    def reg_loss(self, weights):
        # <подсчет второго слагаемого из формулы>
        return self.lambda_ * ((weights**2).sum())

    def forward(self, y_pred, y_true, weights):
        return self.data_loss(y_pred, y_true) + self.reg_loss(weights)

In [ ]:
y_pred = torch.tensor([-0.5, 1, 1.7])
y_true = torch.tensor([0, 0.6, 2.3])
weights = torch.normal(0, 5, (10, 1))

In [ ]:
MSERegularized(lambda_ = 0.1).forward(y_pred = y_pred, y_true = y_true, weights = weights)

tensor(13.3629)

## Обратная связь
- [x] Хочу получить обратную связь по решению